### ISSUE TITLE
singledispatchmethod doesn't work with classmethod

### ISSUE THREAD

**Issue by askerka** [ikalnytskyi/singledispatchmethod#2]
Hi!
I'm not sure why is the reason behind but the example just from the README is not working for me:

```python
from singledispatchmethod import singledispatchmethod

class Negator:

    @singledispatchmethod
    @classmethod
    def neg(cls, arg):
        raise NotImplementedError("Cannot negate a")

    @neg.register
    @classmethod
    def _(cls, arg: int):
        return -arg

    @neg.register
    @classmethod
    def _(cls, arg: bool):
        return not arg
```

```bash
Traceback (most recent call last):
  File "/.pyenv/versions/3.7.13/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 3, in <module>
  File "<input>", line 12, in Negator
  File "/venv/lib/python3.7/site-packages/singledispatchmethod.py", line 64, in register
    return self.dispatcher.register(cls, func=method)
  File "/.pyenv/versions/3.7.13/lib/python3.7/functools.py", line 817, in register
    f"Invalid first argument to `register()`: {cls!r}. "
TypeError: Invalid first argument to `register()`: <classmethod object at 0x1043ccd48>. Use either `@register(some_class)` or plain `@register` on an annotated function.
```

**Comment by ikalnytskyi** [comment]
Hey @askerka,

Thank you for reporting the issue! I'm sorry for providing misleading information in the README, I just copied over that from the official Python 3.8 docs: https://docs.python.org/3.8/library/functools.html#functools.singledispatchmethod

I decided to check the upstream first and it turns out that the very same example does not work on vanilla Python 3.8 too. Check out the following output:

```
$ sudo docker pull python:3.8
$ sudo docker run --rm -ti python:3.8 python
Python 3.8.16 (default, Dec 21 2022, 19:32:01) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from functools import singledispatchmethod
>>>
>>> class Negator:
...     @singledispatchmethod
...     @classmethod
...     def neg(cls, arg):
...         raise NotImplementedError("Cannot negate a")
...     @neg.register
...     @classmethod
...     def _(cls, arg: int):
...         return -arg
...     @neg.register
...     @classmethod
...     def _(cls, arg: bool):
...         return not arg
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 8, in Negator
  File "/usr/local/lib/python3.8/functools.py", line 907, in register
    return self.dispatcher.register(cls, func=method)
  File "/usr/local/lib/python3.8/functools.py", line 849, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`: <classmethod object at 0x7f0fa6ec5910>. Use either `@register(some_class)` or plain `@register` on an annotated function.
```

I also discovered that it has been fixed in Python 3.9 by the following patch: https://github.com/python/cpython/commit/25a12aac4de819745dfc64664ba183a5784b5a81.

The issue actually lies in built-in `functools.singledispatch` on which `singledispatchmethod` relies on. I'm sorry to say, but I don't think I want to complicate this backport by either monkey-patching `functools.singledispatch` or carrying over its own copy. Not when it doesn't work in Python 3.8 too.

The workaround would be as simple as avoid using type annotations for dispatch and explicitly pass it to `.register()` call. E.g:

```python
class Negator:
    @singledispatchmethod
    @classmethod
    def neg(cls, arg):
        raise NotImplementedError("Cannot negate a")

    @neg.register(int)
    @classmethod
    def _(cls, arg: int):
        return -arg

    @neg.register(bool)
    @classmethod
    def _(cls, arg: bool):
        return not arg
```
